project_id = "ioktiqcffungtlsmlkcv"

[functions.citation-chat]
verify_jwt = false

[functions.case-law-search]
verify_jwt = false

[functions.legal-qa]
verify_jwt = false

[functions.embed-legal-source]
verify_jwt = false

[functions.search-legal-sources]
verify_jwt = false

[functions.convert-doc]
verify_jwt = false
